# Generated by Django 4.2.16 on 2024-12-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liname', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('concentracion', models.CharField(max_length=30)),
                ('forma', models.CharField(choices=[('amp', 'Ampolla'), ('com', 'Comprimido'), ('fco', 'Frasco'), ('tub', 'Tubo')], default='com', max_length=3)),
                ('habilitado', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=35)),
                ('paterno', models.CharField(max_length=35)),
                ('materno', models.CharField(max_length=35)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('dosis', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.medicamento')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.paciente')),
            ],
        ),
    ]
