# Generated by Django 4.2.16 on 2024-12-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='id_medicamento',
            new_name='medicamento',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='id_medico',
            new_name='medico',
        ),
        migrations.RenameField(
            model_name='receta',
            old_name='id_paciente',
            new_name='paciente',
        ),
    ]
