# Generated by Django 5.1.3 on 2024-12-07 02:49

import recetas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_alter_medicamento_descripcion_alter_medico_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, validators=[recetas.validators.validar_nulos, recetas.validators.validar_letra]),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='descripcion',
            field=models.CharField(max_length=100, validators=[recetas.validators.validar_nulos, recetas.validators.validar_letra]),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='forma',
            field=models.CharField(choices=[('amp', 'Ampolla'), ('com', 'Comprimido'), ('fco', 'Frasco'), ('tub', 'Tubo'), ('bol', 'Bolsa'), ('pza', 'Pieza')], default='com', max_length=3),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(max_length=100, validators=[recetas.validators.validar_nulos, recetas.validators.validar_letra]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.CharField(max_length=12, unique=True, validators=[recetas.validators.validar_numero]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=35, validators=[recetas.validators.validar_nulos, recetas.validators.validar_letra]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paterno',
            field=models.CharField(max_length=35, validators=[recetas.validators.validar_nulos, recetas.validators.validar_letra]),
        ),
    ]
